# Generated by Django 5.1.5 on 2025-03-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Capacity must be greater than zero'),
        ),
    ]
