# Generated by Django 5.1.5 on 2025-02-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
