# Generated by Django 5.1.5 on 2025-03-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_capacity'),
        ('events', '0003_event_cancelled'),
    ]

    operations = [
    ]
